[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/n8n-proxy/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://digestai.netlify.app"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Environment, X-Force-Proxy"
    Access-Control-Allow-Credentials = "true"

# Handle preflight requests
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://digestai.netlify.app"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Environment, X-Force-Proxy"
    Access-Control-Max-Age = "86400"