[build]
  command = "npm run netlify-build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_NHOST_SUBDOMAIN = "pmdddjhfyuqnpddamxhh"
  VITE_NHOST_REGION = "ap-south-1"
  # Add your n8n webhook URLs here when ready